---

- name: Ensure dir exists
  file: path=/home/vagrant/myapp state=directory

- name: app.py
  template:
    src: app.j2
    dest: '/home/vagrant/myapp/app.py'

- name: requirements.txt
  template:
    src: requirements.j2
    dest: '/home/vagrant/myapp/requirements.txt'

- name: Dockerfile
  template:
    src: Dockerfile.j2
    dest: '/home/vagrant/myapp/Dockerfile'

- name: Build an image
  docker_image:
    path: /home/vagrant/myapp
    name: myapp
    tag: latest

- name: Create Myapp container
  docker_container:
    name: myapp
    image: myapp
    network_mode: host
