---

- name: Install python setup tools
  yum:
    name: python-setuptools

- name: Install python devel
  yum:
    name: python-devel

- name: Install mysql devel
  yum:
    name: mysql-devel

- name: Install Pypi
  easy_install:
    name: pip

- name: Install docker-py
  pip:
    name: docker-py
    version: 1.9.0

- name: Install Docker
  yum:
    name: docker
    state: latest

- name: Make sure Docker is running
  service:
    name: docker
    state: running
